[language-server.ty]
command = "ty"
args = ["server"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.zls]
command = "zls"

[[language]]
name = "python"
language-servers = ["ty"]
file-types = ["py", "pyi", { glob = "*.py" }]
auto-format = true
formatter = { command = "ruff", args = ["format", "--stdin-filename", "{buffer_path}"] }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
formatter = { command = "cargo", args = ["fmt", "--quiet"] }
rulers = [100]

[[language]]
name = "zig"
language-servers = ["zls"]
auto-format = true
formatter = { command = "zig", args = ["fmt", "--stdin", "--color", "off"] }
indent = { tab-width = 4, unit = "    " }
