---
# Homepage Services Configuration
# Organized by category with proper links and Docker integration

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.lab.lan
        description: Media Server - Movies & TV Shows
        server: my-docker
        container: jellyfin

    - Immich:
        icon: immich.png
        href: http://immich.lab.lan
        description: Photo & Video Management
        server: my-docker
        container: immich_server

- Media Automation:
    - Sonarr:
        icon: sonarr.png
        href: http://sonarr.lab.lan
        description: TV Show Manager
        server: my-docker
        container: sonarr

    - Radarr:
        icon: radarr.png
        href: http://radarr.lab.lan
        description: Movie Manager
        server: my-docker
        container: radarr

    - Prowlarr:
        icon: prowlarr.png
        href: http://prowlarr.lab.lan
        description: Indexer Manager
        server: my-docker
        container: prowlarr

    - Bazarr:
        icon: bazarr.png
        href: http://bazarr.lab.lan
        description: Subtitle Manager
        server: my-docker
        container: bazarr

    - qBittorrent:
        icon: qbittorrent.png
        href: http://qbittorrent.lab.lan
        description: Torrent Client
        server: my-docker
        container: qbittorrent

- Network & Infrastructure:
    - Pi-hole:
        icon: pi-hole.png
        href: http://pihole.lab.lan
        description: Network-wide Ad Blocker & DNS
        server: my-docker
        container: pihole

    - Traefik:
        icon: traefik.png
        href: http://traefik.lab.lan
        description: Reverse Proxy & Load Balancer
        server: my-docker
        container: traefik

    - Portainer:
        icon: portainer.png
        href: http://portainer.lab.lan
        description: Docker Management
        server: my-docker
        container: portainer

- AI & Productivity:
    - Open WebUI:
        icon: openwebui.png
        href: http://openwebui.lab.lan
        description: AI Chat Interface
        server: my-docker
        container: openwebui

    - Siyuan:
        icon: si-glyph:notebook.png
        href: http://siyuan.lab.lan
        description: Note Taking & Knowledge Base
        server: my-docker
        container: siyuan

    - Excalidraw:
        icon: excalidraw.png
        href: http://excalidraw.lab.lan
        description: Collaborative Whiteboard & Diagrams
        server: my-docker
        container: excalidraw

- Monitoring:
    - Watchtower:
        icon: watchtower.png
        href: "#"
        description: Automatic Container Updates
        server: my-docker
        container: watchtower
