format = """
$kubernetes$directory$git_branch$git_status$python$cmd_duration
$character
"""

[kubernetes]
style = "bg:#8AADF4 fg:black bold"
format = '[[î‚¶](#8AADF4) $context :: $namespace [î‚´](#8AADF4)]($style)'
disabled = false

[directory]
style = "bg:#DDB6F2 fg:black bold"
format = "[[î‚¶](#DDB6F2) $path [î‚´](#DDB6F2)]($style)"

[python]
symbol = "ğŸ"
style = "bg:#B4BEFE fg:black bold"
format = '[([î‚¶](#B4BEFE) $symbol$virtualenv [î‚´](#B4BEFE))]($style)'

[rust]
symbol = "ğŸ¦€"
style = "bg:#F28FAD fg:black bold"
format = '[([î‚¶](#F28FAD) $symbol$version [î‚´](#F28FAD))]($style)'


[git_branch]
symbol = "ï˜"
style = "bg:#FDB6F5 fg:black bold"
format = '[[î‚¶](#FDB6F5) $symbol $branch]($style)'

[git_status]
style = "bg:#FDB6F5 fg:black bold"
conflicted = "[ ï— ](red bg:#FDB6F5)"
ahead = " ï¡ "
behind = " ï¢ "
diverged = " ï— "
untracked = "[ ï™ ](green bg:#FDB6F5)"
staged = " ï˜ "
modified = "[ ïª ](yellow bg:#FDB6F5)"
stashed = " ï¤ "
format = '[(#FDB6F5) $all_status$ahead_behind [î‚´](#FDB6F5)]($style)'

[cmd_duration]
style = "fg:black bg:#8AADF4 bold"
format = "[[î‚¶](#8AADF4) $duration [î‚´](#8AADF4)]($style)"

[character]
error_symbol = "[â•°â”€îŠ…](bold #F28FAD)"
success_symbol = "[â•°â”€îŠ…](bold #A6E3A1)"
