git:
  pagers:
    - colorArg: always
      pager: delta --dark --side-by-side --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  sidePanelWidth: 0.2
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  nerdFontsVersion: "3"
